### ISSUE TITLE
now stack tracing immediately on opening JetBrains latest EAP on project

### ISSUE THREAD

**Issue by narration-sd** [bluelovers/idea-run-typescript#24]
I'm using PhpStorm for TypeScript and all things node/es6/server/electron; it has all the capacities of WebStorm/IDEA for this.

The just-released new EAP explodes a bit on your plugin.  I've disabled it for the present.

Here's the link  and version card:

[https://www.jetbrains.com/phpstorm/download/download-thanks.html?type=eap&platform=windows&build=212.3724.24&code=PS](https://www.jetbrains.com/phpstorm/download/download-thanks.html?type=eap&platform=windows&build=212.3724.24&code=PS)

![eap-version-card](https://user-images.githubusercontent.com/247945/120899989-5474f380-c5e7-11eb-89e9-0004f22eb4cb.png)

Here's the stack trace:

update failed for AnAction(io.plugin.tsnode.action.DebugTsAction) with ID=io.plugin.tsnode.action.DebugTsAction

java.lang.NullPointerException: null cannot be cast to non-null type com.intellij.openapi.vfs.VirtualFile
	at io.plugin.tsnode.action.TsAction.update(TsAction.kt:91)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$1(ActionUtil.java:126)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:129)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:557)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$updateActionReal$7(ActionUpdater.java:130)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$callAction$9(ActionUpdater.java:183)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$callAction$10(ActionUpdater.java:181)
	at com.intellij.openapi.actionSystem.impl.ActionUpdateEdtExecutor.lambda$computeOnEdt$0(ActionUpdateEdtExecutor.java:44)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:793)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:349)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:905)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:774)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:435)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:793)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:483)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by bluelovers** [comment]
are u installed nodejs plugin?

**Comment by narration-sd** [comment]
yes, png here showing it.  

Would remind, this fault only started occurring when I upgraded to the last EAP (early access). 
I had been running always the previous EAPs before -- I  have a license, but like to help their development.
Of course, some plugins updated to match this EAP, also as usual. I don't think Nodejs was one of those.

Here's the picture:

![nodejs-installed](https://user-images.githubusercontent.com/247945/120908784-efd78a00-c622-11eb-9b49-8f5c8466a752.png)

**Comment by bluelovers** [comment]
oh see it, that error not affect use this plugin can be ignore it

**Comment by bluelovers** [comment]
@narration-sd try install new version from github

https://github.com/bluelovers/idea-run-typescript#install

**Comment by narration-sd** [comment]
hello @bluelovers  -- things were a little confusing, so I will make simple :)

- I had some trouble occur over other plugins after installing your update, but this became suspicious because they remained after disabling it again. 
- so, I used Jetbrains File>Invalidate Caches... , checking all options. This restarts the IDE with no caches.
- indexing after this produced no problems, with other plugins
- I then re-installed and re-enabled idea-run-typescript
- I repeated the Invalidate Caches and retart
- no problem appeared in indexing now

So I think you are good.  Here are a few conclusions
- it appears there was something the matter with my indexes
- it's possible this was true before, but also possible idea-run-javascript caused them by exceptioning during indexing
- your 23e6903 commit appears to be published as well as being the release zip download, if the Plugins settings are telling the truth.  Either way, I think you are now fine :)

Thank you for such rapid and careful attentionk @bluelovers 
Best, Clive

**Comment by bluelovers** [comment]
i install jar version and it also can update from jetbrains too in yesterday

no need reset cache but after install, restart ide maybe will be better
or close all project before install/update plugin

sometime plugin need to install twice if it is didn't install well ( plugin panel will tell u , u still in old version )

**Comment by narration-sd** [comment]
Thanks, all appears to be working fine now, and I am on the Jetbrain/jar release I think for sure.

You might want to know that they discovered the problem I reported for the EAP update two days ago, and it did not involve your plugin at all. So probably the index corruption came from that other issue, as it was at a critical time.

Clearing the caches can be a good move when there's trouble, yes. The only consequence is that you lose Local History, so there's a choice we can make.

Appreciating your work, @bluelovers -- kind of long experienced person here :)
