### ISSUE TITLE
Error in WebStorm

### ISSUE THREAD

**Issue by xmasuhai** [bluelovers/idea-run-typescript#51]
WebStorm 2024.2.3 Build #WS-242.23339.15, built on September 25, 2024
win11
version: 2024.08.16-1

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.plugin.tsnode.action.DebugTsAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: io.plugin.tsnode]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```

**Comment by f1v3** [comment]
The exact same Error occurs also in IntelliJ Ultimate:

IntelliJ IDEA 2024.2.4 (Ultimate Edition)
Build #IU-242.23726.103, built on October 23, 2024

**Comment by alex-at-cascade** [comment]
Also PhpStorm

PhpStorm 2024.2.4
Build #PS-242.23726.107, built on October 23, 2024

**Comment by vrinceanuvalentin** [comment]
Can confirm this for Webstorm on macOS

```
WebStorm 2024.2.4
Build #WS-242.23726.96, built on October 22, 2024
macOS 15.0.1
